---
###
# ec2_provision_group_db.yml
#
- name: "Provision primary db security group"
  local_action:
    module: ec2_group
    name: "{{ item.sec_group }}"
    description: "Access {{ item.sec_group }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        from_port: "{{ ssh_from_port }}"
        to_port: "{{ ssh_to_port}}"
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 3306
        to_port: 3306
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        type: all
        cidr_ip: 0.0.0.0/0

  with_items: instances
  when: instances
  when: item.tags == 'db' or item.tags == 'db_replication'
  tags:
    - ec2
    - db
    - sec_group
