---
###
# Database Provision
#
- name: EC2 Provisioning of CentOS + MySQL
  hosts: localhost
  connection: local 
  gather_facts: False
  vars_files:
    - root_vars/vars.yml
    - root_vars/db_vars.yml

  vars:
    security_group: db_sec_group

  tasks:
    - include: tasks/create_db_sec_group.yml
    - include: tasks/provision_db_ec2_centos.yml
    #- include: tasks/wait_2_minutes.yml



###
# Database Configure
#
- name: Configuring of CentOS + MySQL
  hosts: mysql_instances
  user: root
  sudo: true
  vars_files:
    - root_vars/vars.yml
    - root_vars/db_vars.yml

  vars:
    security_group: db_sec_group

  tasks:
    - include: tasks/secure_centos.yml
    - include: tasks/common_centos.yml
    - include: tasks/install_mysql.yml

  handlers:
    - name: Restart sshd
      action: service name=ssh state=restarted
      tags: common

    - name: restart ntpd
      service: name=ntpd state=restarted



#############################################3
###
# Web Provision
#
- name: Provision CentOS + RVM + RUBY 2 + NGINX
  hosts: localhost
  connection: local 
  gather_facts: False
  vars_files:
    - root_vars/vars.yml
    - root_vars/web_vars.yml

  vars:
    security_group: web_sec_group

  tasks:
    - include: tasks/create_web_sec_group.yml
    - include: tasks/provision_web_ec2_centos.yml
    #- include: tasks/wait_2_minutes.yml

###
# Web Configure
#
- name: Configuring of CentOS + RVM + RUBY 2 + NGINX
  hosts: web_instances
  user: root
  sudo: true
  vars_files:
    - root_vars/vars.yml
    - root_vars/web_vars.yml

  vars:
    security_group: web_sec_group
    ruby_version: "2.1.3"
    rvm_path: "/usr/local/rvm/gems/ruby-{{ ruby_version }}/bin:/usr/local/rvm/gems/ruby-{{ ruby_version }}@global/bin:/usr/local/rvm/rubies/ruby-{{ ruby_version }}/bin:/usr/local/rvm/bin"

  tasks:
    #- include: tasks/secure_centos.yml
    #- include: tasks/common_centos.yml
    #- include: tasks/install_rvm.yml
    - include: tasks/install_shortbread.yml
    #- include: tasks/install_nginx.yml

  handlers:
    ###
    # restart sshd service
    - name: Restart sshd
      action: service name=ssh state=restarted
      tags: service_restart

    ###
    # ensure that Nginx is started
    #
    - name: start nginx
      service: name=nginx state=started
      tags: 
    ###
    # restart Nginx    
    #
    - name: restart nginx
      service: name=nginx state=restarted
      tags: service_started
    ###
    # restart time service          
    #
    - name: restart ntpd
      service: name=ntpd state=restarted
      tags: service_restart
