---
##
# Access Message (SSH)
#
- name: Access Message
  action: copy src=issue.net dest=/etc/issue.net mode=755
  tags: common

##
# Banner Message
#
- name: Banner Message
  action: copy src=motd dest=/etc/motd mode=755
  tags: common

##
# Yum update all 
#
- name: update yum cache
  yum: name=* state=latest

##
# Support EPEL (Extra Packages for Enterprise Linux) - needed sometimes if CentOS version < 7
#
#- name: install extras
#  yum: name=epel-release state=latest


- name: be sure ntp is installed
  yum: pkg=ntp state=installed
  tags: ntp

#- name: be sure ntp is configured
#  template: src=files/ntp.conf.j2 dest=/etc/ntp.conf
#  notify:
#    - restart ntpd
#  tags: ntp

- name: be sure ntpd is running and enabled
  service: name=ntpd state=running enabled=yes
  tags: ntp